// web_new/src/components/Layout.tsx
import React from 'react';

interface LayoutProps {
  children: React.ReactNode[];
  isWideScreen: boolean;
}

/**
 * Responsive layout component
 * Wide screen: horizontal split
 * Narrow screen: vertical stack
 */
export function Layout({ children, isWideScreen }: LayoutProps): React.JSX.Element {
  const [treeMap, cardPreview] = children;

  if (isWideScreen) {
    return (
      <div className="layout layout-wide">
        <div className="layout-section treemap-section">{treeMap}</div>
        <div className="layout-section preview-section">{cardPreview}</div>
      </div>
    );
  }

  return (
    <div className="layout layout-narrow">
      <div className="layout-section treemap-section">{treeMap}</div>
      <div className="layout-section preview-section">{cardPreview}</div>
    </div>
  );
}

// web_new/src/components/Layout.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  let {
    isWideScreen,
    treemap,
    preview,
  }: { isWideScreen: boolean; treemap: Snippet; preview: Snippet } = $props();
</script>

<div class={['layout', isWideScreen ? 'layout-wide' : 'layout-narrow']}>
  <div class="treemap-section">
    {@render treemap()}
  </div>
  <div class="preview-section">
    {@render preview()}
  </div>
</div>

<style>
  /* Responsive layout styles */
  .layout {
    height: 100vh;
    display: flex;
    justify-content: stretch;
    align-items: stretch;
    background-color: #f5f5f5;
  }

  /* Wide screen layout (horizontal split) */
  .layout-wide {
    flex-direction: row;
  }

  .layout-wide .treemap-section {
    flex: 7 7 0;
    border-right: 1px solid #ddd;
    overflow: hidden; /* Prevent sections from expanding */
    min-width: 0;
  }

  .layout-wide .preview-section {
    flex: 3 3 0;
    overflow: hidden; /* Prevent sections from expanding */
    min-width: 0;
  }

  /* Narrow screen layout (vertical stack) */
  .layout-narrow {
    flex-direction: column;
  }

  .layout-narrow .treemap-section {
    flex: 6 6 0;
    border-bottom: 1px solid #ddd;
    min-height: 0; /* Allow flex item to shrink */
  }

  .layout-narrow .preview-section {
    flex: 4 4 0;
    min-height: 0; /* Allow flex item to shrink */
  }
</style>
