// web_new/src/components/PerformanceMonitor.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  let { cardCount, isVisible }: { cardCount: number; isVisible: boolean } = $props();

  let frameCount = $state(0);
  let fps = $state(0);
  let lastTime = $state(0);
  let animationFrameId: number;

  onMount(() => {
    const measureFPS = (currentTime: number) => {
      frameCount++;

      if (currentTime - lastTime >= 1000) {
        fps = Math.round((frameCount * 1000) / (currentTime - lastTime));
        frameCount = 0;
        lastTime = currentTime;
      }

      animationFrameId = requestAnimationFrame(measureFPS);
    };

    lastTime = performance.now();
    animationFrameId = requestAnimationFrame(measureFPS);

    return () => {
      if (animationFrameId) {
        cancelAnimationFrame(animationFrameId);
      }
    };
  });
</script>

{#if isVisible}
  <div class="performance-monitor">
    <div class="performance-stats">
      <div>Cards: {cardCount}</div>
      <div>FPS: {fps}</div>
      <div>
        Memory: {Math.round(
          (performance as unknown as { memory: { usedJSHeapSize: number } }).memory
            ?.usedJSHeapSize / 1048576
        ) || 'N/A'} MB
      </div>
    </div>
  </div>
{/if}

<style>
  /* Performance Monitor */
  .performance-monitor {
    position: fixed;
    bottom: 10px;
    right: 10px;
    background: rgba(0, 0, 0, 0.8);
    color: white;
    padding: 10px;
    border-radius: 4px;
    font-family: monospace;
    font-size: 12px;
    z-index: 1000;
  }

  .performance-stats > div {
    margin: 2px 0;
  }
</style>

// web_new/src/components/PerformanceMonitor.tsx
import React, { useEffect, useState } from 'react';

interface PerformanceMonitorProps {
  cardCount: number;
  isVisible?: boolean;
}

/**
 * Performance monitoring component to help identify bottlenecks
 */
export function PerformanceMonitor({
  cardCount,
  isVisible = false,
}: PerformanceMonitorProps): React.JSX.Element | null {
  const [metrics, setMetrics] = useState({ fps: 0, memory: 0, layoutTime: 0, renderTime: 0 });

  useEffect(() => {
    if (!isVisible) return;

    let frameCount = 0;
    let lastTime = performance.now();
    let animationFrameId: number;

    const measureFPS = () => {
      const currentTime = performance.now();
      frameCount++;

      if (currentTime - lastTime >= 1000) {
        const fps = Math.round((frameCount * 1000) / (currentTime - lastTime));

        // Get memory usage if available
        const memory = (performance as unknown as { memory?: { usedJSHeapSize: number } }).memory
          ? Math.round(
              (performance as unknown as { memory: { usedJSHeapSize: number } }).memory
                .usedJSHeapSize / 1048576
            )
          : 0;

        setMetrics(prev => ({ ...prev, fps, memory }));

        frameCount = 0;
        lastTime = currentTime;
      }

      animationFrameId = requestAnimationFrame(measureFPS);
    };

    animationFrameId = requestAnimationFrame(measureFPS);

    return () => {
      if (animationFrameId) {
        cancelAnimationFrame(animationFrameId);
      }
    };
  }, [isVisible]);

  if (!isVisible) return null;

  return (
    <div className="performance-monitor">
      <div className="performance-stats">
        <div>Cards: {cardCount}</div>
        <div>FPS: {metrics.fps}</div>
        <div>Memory: {metrics.memory}MB</div>
        <div>Layout: {metrics.layoutTime}ms</div>
        <div>Render: {metrics.renderTime}ms</div>
      </div>
    </div>
  );
}
