// web_new/src/components/TreeMap.tsx
import React, { useRef, useEffect, useState, useCallback } from 'react';
import * as d3 from 'd3';
import { CardGroup } from '../types/card';
import { TreeMapRect } from '../types/treemap';
import { useTreeMap } from '../hooks/useTreeMap';
import {
  getRetentionColor,
  getRetentionBorderColor,
  getContrastTextColor,
  interpolateColor,
} from '../utils/color';
import { retentionColors } from '../utils/colorConfig';
import { debounce } from '../utils/performance';
import { PERFORMANCE_CONFIG } from '../utils/performanceConfig';
import './TreeMap.css';

interface TreeMapProps {
  group: CardGroup;
  selectedGroupPath: string[] | null;
  onCardSelect: (cardId: string | null) => void;
  selectedCardId: string | null;
}

/**
 * TreeMap visualization component using D3.js
 */
export function TreeMap({
  group,
  selectedGroupPath,
  onCardSelect,
  selectedCardId,
}: TreeMapProps): React.JSX.Element {
  const svgRef = useRef<SVGSVGElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const svgContainerRef = useRef<HTMLDivElement>(null);
  const [dimensions, setDimensions] = useState({ width: 0, height: 0 });
  const [isCalculating, setIsCalculating] = useState(false);

  // Calculate dimensions based on SVG container only
  useEffect(() => {
    const updateDimensions = (): void => {
      if (svgContainerRef.current) {
        const { width, height } = svgContainerRef.current.getBoundingClientRect();
        // Only update if dimensions actually changed
        if (width !== dimensions.width || height !== dimensions.height) {
          setDimensions({ width, height });
        }
      }
    };

    // Use debounced resize handler
    const debouncedResize = debounce(updateDimensions, PERFORMANCE_CONFIG.RESIZE_DEBOUNCE_MS);

    updateDimensions();
    window.addEventListener('resize', debouncedResize);

    // Use ResizeObserver for more efficient dimension tracking
    let resizeObserver: ResizeObserver | null = null;
    if (svgContainerRef.current && 'ResizeObserver' in window) {
      resizeObserver = new ResizeObserver(debouncedResize);
      resizeObserver.observe(svgContainerRef.current);
    }

    return () => {
      window.removeEventListener('resize', debouncedResize);
      if (resizeObserver) {
        resizeObserver.disconnect();
      }
    };
  }, [dimensions.width, dimensions.height]);

  // Calculate TreeMap layout with loading state
  const treeMapLayout = useTreeMap(group, dimensions.width, dimensions.height, selectedGroupPath);

  // Show loading state when TreeMap is being calculated
  useEffect(() => {
    setIsCalculating(true);
    const timer = setTimeout(() => setIsCalculating(false), 100);
    return () => clearTimeout(timer);
  }, [treeMapLayout]);

  // Apply additional optimizations for high card counts
  const isHighCardCount = group.totalCards > PERFORMANCE_CONFIG.HIGH_CARD_COUNT_THRESHOLD;

  // Memoize click handler to prevent unnecessary re-renders
  const handleNodeClick = useCallback(
    (_: React.MouseEvent, d: TreeMapRect) => {
      // Only select individual cards, not groups
      if (d.data.cardData) {
        onCardSelect(d.data.cardData.uniqueId);
      }
    },
    [onCardSelect]
  );

  // Render TreeMap using D3
  useEffect(() => {
    if (!treeMapLayout || !svgRef.current) return;

    const svg = d3.select(svgRef.current);

    // Clear previous content
    svg.selectAll('*').remove();

    // Use D3 join pattern for efficient updates of card nodes
    const nodeGroups = svg
      .selectAll<SVGGElement, TreeMapRect>('g.treemap-node')
      .data(
        treeMapLayout.nodes,
        (d: TreeMapRect) => d.data.cardData?.uniqueId || d.data.path.join('-')
      );

    // Remove old nodes
    nodeGroups.exit().remove();

    // Create new nodes
    const nodeEnter = nodeGroups
      .enter()
      .append('g')
      .attr('transform', d => `translate(${d.x0},${d.y0})`)
      .attr('class', 'treemap-node')
      .style('cursor', 'pointer')
      .on('click', handleNodeClick);

    // Precompute colors to reduce function calls
    const getNodeStyles = (d: TreeMapRect) => {
      const isPaused = d.data.cardData && d.data.cardData.paused;
      const isSelected = d.data.cardData && selectedCardId === d.data.cardData.uniqueId;

      return {
        fill: getRetentionColor(d.data.averageRetention),
        stroke: isPaused ? '#ff0000' : getRetentionBorderColor(d.data.averageRetention),
        strokeWidth: isPaused ? 2 : 0.5,
        className:
          `treemap-rect ${isSelected ? 'selected' : ''} ${isPaused ? 'paused' : ''}`.trim(),
      };
    };

    // Add rectangles for new nodes
    nodeEnter
      .append('rect')
      .attr('width', d => d.x1 - d.x0)
      .attr('height', d => d.y1 - d.y0)
      .attr('fill', d => getNodeStyles(d).fill)
      .attr('stroke', d => getNodeStyles(d).stroke)
      .attr('stroke-width', d => getNodeStyles(d).strokeWidth)
      .attr('class', d => getNodeStyles(d).className);

    // Add text labels for new nodes (only for larger nodes)
    // Apply stricter thresholds for high card counts
    const minTextWidth = isHighCardCount
      ? PERFORMANCE_CONFIG.MIN_TEXT_WIDTH * 1.5
      : PERFORMANCE_CONFIG.MIN_TEXT_WIDTH;
    const minTextHeight = isHighCardCount
      ? PERFORMANCE_CONFIG.MIN_TEXT_HEIGHT * 1.5
      : PERFORMANCE_CONFIG.MIN_TEXT_HEIGHT;

    const textNodes = nodeEnter.filter(
      d => d.x1 - d.x0 > minTextWidth && d.y1 - d.y0 > minTextHeight
    );

    textNodes
      .append('text')
      .attr('x', 2)
      .attr('y', 10)
      .attr('fill', d => getContrastTextColor(interpolateColor(d.data.averageRetention)))
      .attr('font-size', '8px')
      .text(d => {
        // For individual cards, show retention percentage
        if (d.data.cardData) {
          return `${Math.round(d.data.averageRetention * 100)}%`;
        }
        // For groups, show group name
        const name = d.data.path[d.data.path.length - 1] || 'Root';
        return name.length > 8 ? name.substring(0, 6) + '...' : name;
      });

    // Update existing nodes
    const nodeUpdate = nodeGroups
      .merge(nodeEnter as d3.Selection<SVGGElement, TreeMapRect, SVGSVGElement, unknown>)
      .attr('transform', d => `translate(${d.x0},${d.y0})`);

    // Update rectangles for existing nodes
    nodeUpdate
      .select('rect')
      .attr('width', d => d.x1 - d.x0)
      .attr('height', d => d.y1 - d.y0)
      .attr('fill', d => getNodeStyles(d).fill)
      .attr('stroke', d => getNodeStyles(d).stroke)
      .attr('stroke-width', d => getNodeStyles(d).strokeWidth)
      .attr('class', d => getNodeStyles(d).className);

    // Update text for existing nodes
    nodeUpdate
      .select('text')
      .attr('fill', d => getContrastTextColor(interpolateColor(d.data.averageRetention)))
      .text(d => {
        if (d.data.cardData) {
          return `${Math.round(d.data.averageRetention * 100)}%`;
        }
        const name = d.data.path[d.data.path.length - 1] || 'Root';
        return name.length > 8 ? name.substring(0, 6) + '...' : name;
      });

    // Render group borders AFTER cards (so they appear on top)
    const groupGroups = svg
      .selectAll('g.treemap-group')
      .data(treeMapLayout.groupNodes)
      .enter()
      .append('g')
      .attr('transform', d => `translate(${d.x0},${d.y0})`)
      .attr('class', 'treemap-group');

    // Add white borders for groups
    groupGroups
      .append('rect')
      .attr('width', d => d.x1 - d.x0)
      .attr('height', d => d.y1 - d.y0)
      .attr('fill', 'none')
      .attr('stroke', 'black')
      .attr('stroke-width', 3);
  }, [treeMapLayout, selectedCardId, handleNodeClick]);

  return (
    <div className="treemap-container" ref={containerRef}>
      <h3>Card Retention TreeMap</h3>
      <div className="treemap-svg-container" ref={svgContainerRef}>
        {isCalculating && <div className="treemap-loading">Calculating layout...</div>}
        <svg
          ref={svgRef}
          width={dimensions.width}
          height={dimensions.height}
          className="treemap-svg"
          style={{ opacity: isCalculating ? 0.5 : 1 }}
        />
      </div>
      <div className="treemap-legend">
        {retentionColors.map(([retention]) => (
          <div key={retention} className="legend-item">
            <span
              className="legend-color"
              style={{ backgroundColor: getRetentionColor(retention) }}
            ></span>
            <span>{Math.round(retention * 100)}%</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// web_new/src/components/TreeMap.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { CardGroup } from '../types/card';
  import type { TreeMapRect } from '../types/treemap';
  import { calculateTreeMap } from '../stores/treeMap';
  import {
    getRetentionColor,
    getRetentionBorderColor,
    getContrastTextColor,
    interpolateColor,
  } from '../utils/color';
  import { retentionColors } from '../utils/colorConfig';
  import { findGroupByPath } from '../utils/groupListBuilder';
  import { debounce } from '../utils/performance';
  import { PERFORMANCE_CONFIG } from '../utils/performanceConfig';

  type Props = {
    group: CardGroup;
    onCardSelect: (cardId: string | null) => void;
    selectedGroupPath: string[];
    selectedCardId: string | null;
  };

  let { group, onCardSelect, selectedGroupPath, selectedCardId }: Props = $props();

  let svgContainerRef: HTMLDivElement;
  let dimensions = $state({ width: 0, height: 0 });

  // Calculate dimensions based on SVG container only
  let resizeObserver: ResizeObserver | null = null;

  onMount(() => {
    // TODO
    const updateDimensions = (): void => {
      if (svgContainerRef) {
        const { width, height } = svgContainerRef.getBoundingClientRect();
        // Only update if dimensions actually changed
        if (width !== dimensions.width || height !== dimensions.height) {
          dimensions = { width, height };
        }
      }
    };

    // Use debounced resize handler
    const debouncedResize = debounce(updateDimensions, PERFORMANCE_CONFIG.RESIZE_DEBOUNCE_MS);

    updateDimensions();
    window.addEventListener('resize', debouncedResize);

    // Use ResizeObserver for more efficient dimension tracking
    if ('ResizeObserver' in window) {
      resizeObserver = new ResizeObserver(debouncedResize);
      resizeObserver.observe(svgContainerRef);
    }

    return () => {
      window.removeEventListener('resize', debouncedResize);
      if (resizeObserver) {
        resizeObserver.disconnect();
      }
    };
  });

  const displayRoot = $derived(findGroupByPath(group, selectedGroupPath));
  // Calculate TreeMap layout
  const treeMapLayout = $derived(
    displayRoot && calculateTreeMap(displayRoot, dimensions.width, dimensions.height)
  );

  // Apply additional optimizations for high card counts
  const isHighCardCount = $derived(group.totalCards > PERFORMANCE_CONFIG.HIGH_CARD_COUNT_THRESHOLD);

  // Helper function to determine if a node should show text
  function shouldShowText(node: TreeMapRect): boolean {
    const width = node.x1 - node.x0;
    const height = node.y1 - node.y0;

    // Apply stricter thresholds for high card counts
    const minTextWidth = isHighCardCount
      ? PERFORMANCE_CONFIG.MIN_TEXT_WIDTH * 1.5
      : PERFORMANCE_CONFIG.MIN_TEXT_WIDTH;
    const minTextHeight = isHighCardCount
      ? PERFORMANCE_CONFIG.MIN_TEXT_HEIGHT * 1.5
      : PERFORMANCE_CONFIG.MIN_TEXT_HEIGHT;

    return width > minTextWidth && height > minTextHeight;
  }

  // Helper function to get text for a node
  function getNodeText(node: TreeMapRect): string {
    // For individual cards, show retention percentage
    if (node.data.cardData) {
      return `${Math.round(node.data.averageRetention * 100)}%`;
    }
    // For groups, show group name
    const name = node.data.path[node.data.path.length - 1] || 'Root';
    return name.length > 8 ? name.substring(0, 6) + '...' : name;
  }

  // Helper function to get node styles
  function getNodeStyles(node: TreeMapRect): {
    fill: string;
    stroke: string;
    strokeWidth: number;
    classList: (string | Record<string, boolean>)[];
  } {
    const isPaused = Boolean(node.data.cardData && node.data.cardData.paused);
    const isSelected = Boolean(
      node.data.cardData && selectedCardId === node.data.cardData.uniqueId
    );

    return {
      fill: getRetentionColor(node.data.averageRetention),
      stroke: isPaused ? '#ff0000' : getRetentionBorderColor(node.data.averageRetention),
      strokeWidth: isPaused ? 2 : 0.5,
      classList: ['treemap-rect', { selected: isSelected, paused: isPaused }],
    };
  }

  // Helper function to get text color
  function getTextNodeColor(node: TreeMapRect): string {
    return getContrastTextColor(interpolateColor(node.data.averageRetention));
  }
</script>

<div class="treemap-container">
  <h3>Card Retention TreeMap</h3>
  <div class="treemap-svg-container" bind:this={svgContainerRef}>
    <svg width={dimensions.width} height={dimensions.height} class="treemap-svg">
      {#if treeMapLayout}
        <!-- Render card nodes -->
        {#each treeMapLayout.nodes as node (node.data.cardData?.uniqueId || node.data.path.join('::'))}
          {@const styles = getNodeStyles(node)}
          {@const text = getNodeText(node)}
          {@const textColor = getTextNodeColor(node)}
          <rect
            class={['treemap-node', ...styles.classList]}
            style:cursor={node.data.cardData ? 'pointer' : 'default'}
            onclick={() => node.data.cardData && onCardSelect(node.data.cardData.uniqueId)}
            role="button"
            tabindex={node.data.cardData ? 0 : undefined}
            onkeydown={e => {
              if (node.data.cardData && (e.key === 'Enter' || e.key === ' ')) {
                e.preventDefault();
                onCardSelect(node.data.cardData.uniqueId);
              }
            }}
            x={node.x0}
            y={node.y0}
            width={node.x1 - node.x0}
            height={node.y1 - node.y0}
            fill={styles.fill}
            stroke={styles.stroke}
            stroke-width={styles.strokeWidth}
          >
            {#if shouldShowText(node)}
              <text x="2" y="10" fill={textColor} font-size="8px">
                {text}
              </text>
            {/if}
          </rect>
        {/each}

        <!-- Render group borders AFTER cards (so they appear on top) -->
        {#each treeMapLayout.groupNodes as groupNode (groupNode.data.path.join('-'))}
          <g transform={`translate(${groupNode.x0},${groupNode.y0})`} class="treemap-group">
            <rect
              width={groupNode.x1 - groupNode.x0}
              height={groupNode.y1 - groupNode.y0}
              fill="none"
              stroke="black"
              stroke-width="3"
            />
          </g>
        {/each}
      {/if}
    </svg>
  </div>
  <div class="treemap-legend">
    {#each retentionColors as [retention] (retention)}
      <div class="legend-item">
        <span class="legend-color" style:background-color={getRetentionColor(retention)}></span>
        <span>{Math.round(retention * 100)}%</span>
      </div>
    {/each}
  </div>
</div>

<style>
  /* TreeMap component styles */
  .treemap-container {
    height: 100%;
    display: flex;
    flex-direction: column;
    padding: 16px;
    background-color: white;
    overflow: hidden; /* Prevent container from expanding */
  }

  .treemap-container h3 {
    margin: 0 0 16px 0;
    color: #333;
    font-size: 18px;
  }

  .treemap-svg-container {
    flex: 1;
    min-height: 0; /* Important for flex child scrolling */
    position: relative;
  }

  .treemap-svg {
    width: 100%;
    height: 100%;
    background-color: #fafafa;
    border: 1px solid #e0e0e0;
    border-radius: 4px;
  }

  .treemap-legend {
    display: flex;
    justify-content: center;
    gap: 24px;
    margin-top: 16px;
    padding: 12px;
    background-color: white;
    border: 1px solid #e0e0e0;
    border-radius: 4px;
  }

  .legend-item {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 14px;
    color: #666;
  }

  .legend-color {
    width: 20px;
    height: 20px;
    border: 1px solid #ccc;
    border-radius: 3px;
  }

  /* Node selection states */
  .treemap-rect.selected {
    stroke: #007bff !important;
    stroke-width: 2px !important;
  }

  .treemap-rect.paused {
    stroke: #ff0000 !important;
    stroke-width: 2px !important;
  }
</style>
